apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: Maven Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Build and test with Maven
        uses: docker://maven:3.9-eclipse-temurin-8
        run: |
          mvn clean test

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-results-pattern: target/surefire-reports/*.xml
          test-results-format: junit
